directory: static
url: /static
debug: True
updater: timestamp
bundles:
    main_js:
        output: build/main.js
        contents:
            - components/jquery/jquery.js
            - components/bootstrap/js/button.js
            - components/bootstrap/js/affix.js
            - components/bootstrap/js/collapse.js
            - components/bootstrap/js/carousel.js
            - components/sequencejs/scripts/jquery.sequence.js
            - components/holderjs/holder.js
            - components/loremjs/lorem.js
            - js/main.js

    main_css:
        filters:
            - less
        output: build/main.css
        contents:
            - components/bootstrap/less/bootstrap.less
            - components/font-awesome/css/font-awesome.css
            - css/sticky-footer.css
            - css/screen.less
